export const weatherDataObject = {
  humidity: {
    name: "Влажность",
    icon: "./public/humidity.svg",
    value: 75,
    designation: "%",
    info: "",
    min: 0,
    max: 100,
  },
  barometr: {
    name: "Давление",
    icon: "./public/barometr.svg",
    value: 761,
    designation: "",
    info: "Повышенное",
    min: 0,
    max: 1000,
  },
  visibility: {
    name: "Видимость",
    icon: "/public/visibility.svg",
    value: 28,
    designation: "км",
    info: "Нормальная",
    min: 0,
    max: 100,
  },
  sunrise: {
    name: "Рассвет",
    icon: "/public/sunrise.svg",
    value: "8:42",
    designation: "",
    info: "Прошло: ",
    changeTime: "02:47",
  },
  sunset: {
    name: "Закат",
    icon: "./public/sunset.svg",
    value: "16:37",
    designation: "",
    info: "Осталось: ",
    changeTime: "05:08",
  },
  wind: {
    name: "Сила ветра",
    icon: "./public/northwest.svg",
    value: 2,
    designation: "мс",
    info: "Cеверо-западный",
  },
};

export const weatherDataArray = [
  {
    id: "humidity",
    name: "Влажность",
    icon: "./public//humidity.svg",
    value: 75,
    designation: "%",
    info: "",
    min: 0,
    max: 100,
  },
  {
    id: "barometr",
    name: "Давление",
    icon: "",
    value: 761,
    designation: "",
    info: "Повышенное",
    min: 0,
    max: 1000,
  },
  {
    id: "visibility",
    name: "Видимость",
    icon: "",
    value: 28,
    designation: "км",
    info: "Нормальная",
    min: 0,
    max: 1000,
  },
  {
    id: "sunrise",
    name: "Рассвет",
    icon: "",
    value: "8:42",
    designation: "",
    info: "Прошло:",
    passed: "02:47",
  },
  {
    id: "sunset",
    name: "Закат",
    icon: "",
    value: "16:37",
    designation: "",
    info: "Осталось:",
    remained: "05:08",
  },
  {
    id: "wind",
    name: "Сила ветра",
    icon: "",
    value: 2,
    designation: "мс",
    info: "Северо-западный",
  },
];
